sonar.projectKey=catdog-danielaquiaro
sonar.projectName=catdog-danielaquiaro
sonar.exclusions=**/node_modules/**,**/*.spec.test.*,**/*.config.*,**/coverage/**
sonar.javascript.lcov.reportPaths=services/backend/coverage/lcov.info,services/frontend/coverage/lcov.info
